//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLine
    {
        public int LineID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> PartID { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual DemandDocument DemandDocument { get; set; }
        public virtual Part Part { get; set; }
    }
}
