//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoServiceDBEntities : DbContext
    {
        public AutoServiceDBEntities()
            : base("name=AutoServiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarOwner> CarOwner { get; set; }
        public virtual DbSet<DemandDocument> DemandDocument { get; set; }
        public virtual DbSet<Diagnostics> Diagnostics { get; set; }
        public virtual DbSet<DocumentLine> DocumentLine { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<Warranty> Warranty { get; set; }
    }
}
